"""community_submissions

Revision ID: 04e618929683
Revises: a1899d9ad279
Create Date: 2026-07-24 11:21:19.580234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04e618929683'
down_revision: Union[str, Sequence[str], None] = 'a1899d9ad279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_submissions',
    sa.Column('tracking_id', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('claimed_type', sa.Text(), nullable=True),
    sa.Column('claimed_title', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitter_email_ciphertext', sa.Text(), nullable=True),
    sa.Column('submitter_email_hash', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.Text(), nullable=False),
    sa.Column('user_agent_hash', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), server_default=sa.text("'received'"), nullable=False),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('job_idempotency_key', sa.Text(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['community_submissions.id'], name=op.f('fk_community_submissions_duplicate_of_id_community_submissions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_submissions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_community_submissions_idempotency_key')),
    sa.UniqueConstraint('tracking_id', name=op.f('uq_community_submissions_tracking_id'))
    )
    op.create_index('ix_community_submissions_canonical_url', 'community_submissions', ['canonical_url'], unique=False)
    op.create_index('ix_community_submissions_created_at', 'community_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_submissions_job_idempotency_key'), 'community_submissions', ['job_idempotency_key'], unique=False)
    op.create_index('ix_community_submissions_state', 'community_submissions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_community_submissions_state', table_name='community_submissions')
    op.drop_index(op.f('ix_community_submissions_job_idempotency_key'), table_name='community_submissions')
    op.drop_index('ix_community_submissions_created_at', table_name='community_submissions')
    op.drop_index('ix_community_submissions_canonical_url', table_name='community_submissions')
    op.drop_table('community_submissions')
    # ### end Alembic commands ###
