"""alerts

Revision ID: 34f0b0e54009
Revises: 1231fd47fb72
Create Date: 2026-07-24 11:51:16.853589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34f0b0e54009'
down_revision: Union[str, Sequence[str], None] = '1231fd47fb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_subscriptions',
    sa.Column('email_ciphertext', sa.Text(), nullable=False),
    sa.Column('email_hash', sa.Text(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('filter_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('cadence', sa.Text(), server_default=sa.text("'daily'"), nullable=False),
    sa.Column('confirm_token_hash', sa.Text(), nullable=True),
    sa.Column('unsubscribe_token_hash', sa.Text(), nullable=True),
    sa.Column('confirm_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_matched_cursor', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_subscriptions')),
    sa.UniqueConstraint('confirm_token_hash', name=op.f('uq_alert_subscriptions_confirm_token_hash')),
    sa.UniqueConstraint('unsubscribe_token_hash', name=op.f('uq_alert_subscriptions_unsubscribe_token_hash'))
    )
    op.create_index(op.f('ix_alert_subscriptions_email_hash'), 'alert_subscriptions', ['email_hash'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_notification_deliveries_listing_id_listings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['alert_subscriptions.id'], name=op.f('fk_notification_deliveries_subscription_id_alert_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('idempotency_key', name='uq_notification_deliveries_idempotency')
    )
    op.create_index(op.f('ix_notification_deliveries_subscription_id'), 'notification_deliveries', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_deliveries_subscription_id'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_alert_subscriptions_email_hash'), table_name='alert_subscriptions')
    op.drop_table('alert_subscriptions')
    # ### end Alembic commands ###
