"""live_discovery

Revision ID: 48f0e210b44e
Revises: 34f0b0e54009
Create Date: 2026-07-24 11:52:50.638011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48f0e210b44e'
down_revision: Union[str, Sequence[str], None] = '34f0b0e54009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_discovery_runs',
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('connector_types', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('result_cap', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('verified_listing_ids', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('ip_hash', sa.Text(), nullable=False),
    sa.Column('cost_units', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_discovery_runs'))
    )
    op.create_index(op.f('ix_live_discovery_runs_request_hash'), 'live_discovery_runs', ['request_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_discovery_runs_request_hash'), table_name='live_discovery_runs')
    op.drop_table('live_discovery_runs')
    # ### end Alembic commands ###
