"""core_schema

Revision ID: a1899d9ad279
Revises: 
Create Date: 2026-07-24 11:03:39.736244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1899d9ad279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('actor_login', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_trace_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_log'))
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_actor_id'), 'admin_audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_request_trace_id'), 'admin_audit_log', ['request_trace_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_target_id'), 'admin_audit_log', ['target_id'], unique=False)
    op.create_table('listings',
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('verification_status', sa.Text(), server_default=sa.text("'needs_review'"), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('search_extra', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('search_document', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'B') || setweight(to_tsvector('english', coalesce(search_extra, '')), 'C')", persisted=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name=op.f('ck_listings_confidence_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings')),
    sa.UniqueConstraint('slug', name=op.f('uq_listings_slug'))
    )
    op.create_index(op.f('ix_listings_kind'), 'listings', ['kind'], unique=False)
    op.create_index('ix_listings_kind_status_published', 'listings', ['kind', 'verification_status', 'published_at'], unique=False)
    op.create_index('ix_listings_last_checked_at', 'listings', ['last_checked_at'], unique=False)
    op.create_index('ix_listings_search_document', 'listings', ['search_document'], unique=False, postgresql_using='gin')
    op.create_index('ix_listings_title_trgm', 'listings', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_listings_verification_status'), 'listings', ['verification_status'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('connector_type', sa.Text(), nullable=False),
    sa.Column('trust_tier', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('polling_policy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('fetch_policy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('credential_ref', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_sources_name'))
    )
    op.create_index(op.f('ix_sources_connector_type'), 'sources', ['connector_type'], unique=False)
    op.create_index(op.f('ix_sources_trust_tier'), 'sources', ['trust_tier'], unique=False)
    op.create_table('ai_offers',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_logo', sa.Text(), nullable=True),
    sa.Column('offer_type', sa.Text(), nullable=False),
    sa.Column('offer_value', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('target_users', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('requirements', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supported_regions', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('official_terms_url', sa.Text(), nullable=False),
    sa.Column('claim_url', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('suitable_reasons', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_ai_offers_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', name=op.f('pk_ai_offers'))
    )
    op.create_index('ix_ai_offers_expires_at', 'ai_offers', ['expires_at'], unique=False)
    op.create_index('ix_ai_offers_offer_type', 'ai_offers', ['offer_type'], unique=False)
    op.create_index('ix_ai_offers_supported_regions', 'ai_offers', ['supported_regions'], unique=False, postgresql_using='gin')
    op.create_index('ix_ai_offers_tags', 'ai_offers', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('discovery_signals',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('signal_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_urls', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('extracted_information', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('review_state', sa.Text(), server_default=sa.text("'needs_review'"), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_discovery_signals_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovery_signals')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_discovery_signals_source_external')
    )
    op.create_index('ix_discovery_signals_review_state', 'discovery_signals', ['review_state'], unique=False)
    op.create_index(op.f('ix_discovery_signals_source_id'), 'discovery_signals', ['source_id'], unique=False)
    op.create_table('hackathons',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('organizer', sa.Text(), nullable=False),
    sa.Column('organizer_logo', sa.Text(), nullable=True),
    sa.Column('registration_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('eligible_countries', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('eligibility', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('team_min', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('team_max', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('prize_value', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('prize_currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('technologies', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('official_url', sa.Text(), nullable=False),
    sa.Column('suitable_reasons', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('effort_estimate', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('prize_value >= 0', name=op.f('ck_hackathons_prize_non_negative')),
    sa.CheckConstraint('team_max >= team_min', name=op.f('ck_hackathons_team_max_gte_min')),
    sa.CheckConstraint('team_min >= 1', name=op.f('ck_hackathons_team_min_positive')),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_hackathons_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', name=op.f('pk_hackathons'))
    )
    op.create_index('ix_hackathons_eligibility', 'hackathons', ['eligibility'], unique=False, postgresql_using='gin')
    op.create_index('ix_hackathons_eligible_countries', 'hackathons', ['eligible_countries'], unique=False, postgresql_using='gin')
    op.create_index('ix_hackathons_submission_deadline', 'hackathons', ['submission_deadline'], unique=False)
    op.create_index('ix_hackathons_technologies', 'hackathons', ['technologies'], unique=False, postgresql_using='gin')
    op.create_table('source_queries',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('query_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('curated_accounts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"interval_seconds": 86400}\'::jsonb'), nullable=False),
    sa.Column('result_cap', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('cost_budget', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_run_cursor', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_queries_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_queries'))
    )
    op.create_index(op.f('ix_source_queries_next_run_at'), 'source_queries', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_source_queries_source_id'), 'source_queries', ['source_id'], unique=False)
    op.create_table('verification_events',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('previous_status', sa.Text(), nullable=True),
    sa.Column('new_status', sa.Text(), nullable=False),
    sa.Column('checked_urls', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('deterministic_checks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.Text(), server_default=sa.text("'system'"), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_verification_events_listing_id_listings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_events'))
    )
    op.create_index('ix_verification_events_listing_created', 'verification_events', ['listing_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_verification_events_listing_id'), 'verification_events', ['listing_id'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_query_id', sa.UUID(), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('discovered_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fetched_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_units', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_crawl_runs_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_query_id'], ['source_queries.id'], name=op.f('fk_crawl_runs_source_query_id_source_queries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_runs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_crawl_runs_idempotency_key'))
    )
    op.create_index(op.f('ix_crawl_runs_source_id'), 'crawl_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_crawl_runs_source_query_id'), 'crawl_runs', ['source_query_id'], unique=False)
    op.create_index(op.f('ix_crawl_runs_status'), 'crawl_runs', ['status'], unique=False)
    op.create_index('ix_crawl_runs_status_started', 'crawl_runs', ['status', 'started_at'], unique=False)
    op.create_index('ix_crawl_runs_trace_id', 'crawl_runs', ['trace_id'], unique=False)
    op.create_table('raw_documents',
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('crawl_run_id', sa.UUID(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'standard'"), nullable=False),
    sa.Column('availability', sa.Text(), server_default=sa.text("'available'"), nullable=False),
    sa.Column('http_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], name=op.f('fk_raw_documents_crawl_run_id_crawl_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_raw_documents_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_documents')),
    sa.UniqueConstraint('content_hash', 'canonical_url', name='uq_raw_documents_hash_url')
    )
    op.create_index('ix_raw_documents_canonical_url', 'raw_documents', ['canonical_url'], unique=False)
    op.create_index('ix_raw_documents_content_hash', 'raw_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_documents_crawl_run_id'), 'raw_documents', ['crawl_run_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_source_id'), 'raw_documents', ['source_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('raw_document_id', sa.UUID(), nullable=False),
    sa.Column('extractor_version', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('cost_units', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_category', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], name=op.f('fk_extraction_runs_raw_document_id_raw_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_runs'))
    )
    op.create_index(op.f('ix_extraction_runs_raw_document_id'), 'extraction_runs', ['raw_document_id'], unique=False)
    op.create_index('ix_extraction_runs_status', 'extraction_runs', ['status'], unique=False)
    op.create_table('listing_sources',
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('raw_document_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('observed_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_listing_sources_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], name=op.f('fk_listing_sources_raw_document_id_raw_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_listing_sources_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_sources')),
    sa.UniqueConstraint('listing_id', 'source_id', 'source_url', name='uq_listing_sources_listing_source_url')
    )
    op.create_index(op.f('ix_listing_sources_listing_id'), 'listing_sources', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_sources_source_id'), 'listing_sources', ['source_id'], unique=False)
    op.create_table('review_items',
    sa.Column('candidate_type', sa.Text(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('candidate_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('assigned_admin_id', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('extraction_run_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], name=op.f('fk_review_items_extraction_run_id_extraction_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_review_items_listing_id_listings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_review_items_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items'))
    )
    op.create_index(op.f('ix_review_items_candidate_id'), 'review_items', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_review_items_candidate_type'), 'review_items', ['candidate_type'], unique=False)
    op.create_index(op.f('ix_review_items_listing_id'), 'review_items', ['listing_id'], unique=False)
    op.create_index(op.f('ix_review_items_priority'), 'review_items', ['priority'], unique=False)
    op.create_index(op.f('ix_review_items_state'), 'review_items', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_items_state'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_priority'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_listing_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_candidate_type'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_candidate_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_listing_sources_source_id'), table_name='listing_sources')
    op.drop_index(op.f('ix_listing_sources_listing_id'), table_name='listing_sources')
    op.drop_table('listing_sources')
    op.drop_index('ix_extraction_runs_status', table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_raw_document_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_raw_documents_source_id'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_crawl_run_id'), table_name='raw_documents')
    op.drop_index('ix_raw_documents_content_hash', table_name='raw_documents')
    op.drop_index('ix_raw_documents_canonical_url', table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index('ix_crawl_runs_trace_id', table_name='crawl_runs')
    op.drop_index('ix_crawl_runs_status_started', table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_status'), table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_source_query_id'), table_name='crawl_runs')
    op.drop_index(op.f('ix_crawl_runs_source_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_verification_events_listing_id'), table_name='verification_events')
    op.drop_index('ix_verification_events_listing_created', table_name='verification_events')
    op.drop_table('verification_events')
    op.drop_index(op.f('ix_source_queries_source_id'), table_name='source_queries')
    op.drop_index(op.f('ix_source_queries_next_run_at'), table_name='source_queries')
    op.drop_table('source_queries')
    op.drop_index('ix_hackathons_technologies', table_name='hackathons', postgresql_using='gin')
    op.drop_index('ix_hackathons_submission_deadline', table_name='hackathons')
    op.drop_index('ix_hackathons_eligible_countries', table_name='hackathons', postgresql_using='gin')
    op.drop_index('ix_hackathons_eligibility', table_name='hackathons', postgresql_using='gin')
    op.drop_table('hackathons')
    op.drop_index(op.f('ix_discovery_signals_source_id'), table_name='discovery_signals')
    op.drop_index('ix_discovery_signals_review_state', table_name='discovery_signals')
    op.drop_table('discovery_signals')
    op.drop_index('ix_ai_offers_tags', table_name='ai_offers', postgresql_using='gin')
    op.drop_index('ix_ai_offers_supported_regions', table_name='ai_offers', postgresql_using='gin')
    op.drop_index('ix_ai_offers_offer_type', table_name='ai_offers')
    op.drop_index('ix_ai_offers_expires_at', table_name='ai_offers')
    op.drop_table('ai_offers')
    op.drop_index(op.f('ix_sources_trust_tier'), table_name='sources')
    op.drop_index(op.f('ix_sources_connector_type'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_listings_verification_status'), table_name='listings')
    op.drop_index('ix_listings_title_trgm', table_name='listings', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_listings_search_document', table_name='listings', postgresql_using='gin')
    op.drop_index('ix_listings_last_checked_at', table_name='listings')
    op.drop_index('ix_listings_kind_status_published', table_name='listings')
    op.drop_index(op.f('ix_listings_kind'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_admin_audit_log_target_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_request_trace_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_actor_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
